all:	TestAVLTree TestSimpleBST

TestAVLTree:	TestAVLTree.cpp
	g++ -std=c++11 -Wall TestAVLTree.cpp -o TestAVLTree
	
TestSimpleBST:	TestSimpleBST.cpp
	g++ -std=c++11 -Wall TestSimpleBST.cpp -o TestSimpleBST
	
clean:
	rm TestAVLTree TestSimpleBST